name: lint-action

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: BCSDLab/.github/.github/actions/setup-node@v1
        with:
          cache: yarn
      - name: Install package
        run: yarn
      - name: Check lint
        run: yarn lint
      - name: Type Check
        run: yarn typecheck
